### PR TITLE
Add proxy option for phantomas

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by rejas** [comment]
sorry to bother, but what is your take on this PR?

**Comment by AvraamMavridis** [comment]
@rejas  oh sorry, my bad, I totally forgot it. Will take a look during the day.

**Comment by AvraamMavridis** [comment]
Will push it later on npm. Thx!

**Comment by rejas** [comment]
Thx, already opened a new PR for a potential v2.3.1 :-)

**Pull request merged**
