### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rejas**
Update all dependencies to get rid of some npm audit warnings, especiall about gulp-connect using event-stream (see https://github.com/dominictarr/event-stream/issues/116)

### CODE REVIEW

**Comment by rejas** [comment]
hi @AvraamMavridis anything I can do to get this merged?

**Comment by AvraamMavridis** [comment]
Hi @rejas , it seems there are conflicts, can you pls have a look? After that I can merge it for sure. Thx a lot.

**Comment by rejas** [comment]
Hi @AvraamMavridis I dont see any conflicts neither here nor on my pc. Could you point me where they appear?

**Comment by AvraamMavridis** [comment]
@rejas  I see this, merge button is deactivated

screen shot 2019-02-18 at 17 21 10

**Comment by rejas** [comment]
Weird, but lets see if my rebase/forcepush unto my branch fixed it on your side too @AvraamMavridis

**Comment by AvraamMavridis** [comment]
@rejas thx a lot, merged.

**Pull request merged**
